"""
Mercury database module.

Discovery, classification, MariaDB connectivity, backup planning,
and policy validation for platform databases.
"""

from mercury.database.core import (
    CATALOG_BY_NAME,
    DEV_SUFFIX,
    PLATFORM_CATALOG,
    PLATFORM_DATABASES,
    PROD_SUFFIX,
    SHARED_AUTHORITY_NAME,
    SOURCE_CATALOG,
    SOURCE_EXAMPLE,
    SOURCE_LIVE,
    SOURCE_LOCAL,
    CatalogEntry,
    DatabaseClassification,
    DatabaseInventory,
    DatabaseRecord,
    DatabaseRole,
    backup_source_entries,
    backup_source_names,
    classify_database,
    configured_database_names,
    entries_by_role,
    exclusion_reason,
    format_entry_line,
    inventory_summary,
    is_live_inventory,
    load_databases_from_file,
    parse_host_port,
    projects_map,
    record_from_name,
)
from mercury.database.discovery import (
    DiscoveryMode,
    discover,
    discover_demo,
    discover_from_config,
)
from mercury.database.display import (
    print_classification,
    print_inventory,
    print_readonly_discovery_plan,
)
from mercury.database.display_pairs import print_prod_dev_pairs
from mercury.database.display_policy import print_policy_report
from mercury.database.pairs import (
    ProdDevPair,
    build_prod_dev_pairs,
    orphan_dev_databases,
    prod_to_dev_name,
)
from mercury.database.planning import (
    DEMO_DATABASES,
    BackupPlanDryRun,
    ExcludedDatabase,
    build_backup_plan,
    build_backup_plan_from_inventory,
    build_demo_backup_plan,
    build_discovered_backup_plan,
)
from mercury.database.policy import (
    PolicyFinding,
    PolicyReport,
    validate_config_policy,
    validate_configured_names_only,
)
from mercury.database.service import DatabaseService, default_service
from mercury.database.mariadb import (
    MariaDbConfigError,
    MariaDbConnectionConfig,
    MariaDbDriverMissingError,
    MariaDbLiveError,
    MariaDbServerProbe,
    discover_databases_live,
    fetch_database_names,
    load_mariadb_config,
    probe_client_tooling,
    probe_mariadb_server,
    resolve_mariadb_target,
    try_load_mariadb_config,
    build_readonly_discovery_plan,
)
from mercury.database.mariadb.access import PlatformAccessReport, build_platform_access_report
from mercury.database.mariadb.inspect import DatabaseInspectResult, inspect_database_on_server

__all__ = [
    "DatabaseService",
    "default_service",
    "DatabaseRecord",
    "DatabaseInventory",
    "CatalogEntry",
    "PLATFORM_CATALOG",
    "PLATFORM_DATABASES",
    "CATALOG_BY_NAME",
    "DEMO_DATABASES",
    "DatabaseRole",
    "DatabaseClassification",
    "classify_database",
    "exclusion_reason",
    "SHARED_AUTHORITY_NAME",
    "PROD_SUFFIX",
    "DEV_SUFFIX",
    "load_databases_from_file",
    "configured_database_names",
    "parse_host_port",
    "DiscoveryMode",
    "discover",
    "discover_from_config",
    "discover_demo",
    "load_mariadb_config",
    "MariaDbConfigError",
    "MariaDbConnectionConfig",
    "discover_databases_live",
    "fetch_database_names",
    "MariaDbLiveError",
    "MariaDbDriverMissingError",
    "MariaDbServerProbe",
    "probe_mariadb_server",
    "resolve_mariadb_target",
    "try_load_mariadb_config",
    "inspect_database_on_server",
    "DatabaseInspectResult",
    "build_platform_access_report",
    "PlatformAccessReport",
    "probe_client_tooling",
    "build_readonly_discovery_plan",
    "print_inventory",
    "print_classification",
    "print_readonly_discovery_plan",
    "print_prod_dev_pairs",
    "print_policy_report",
    "inventory_summary",
    "record_from_name",
    "backup_source_names",
    "backup_source_entries",
    "entries_by_role",
    "format_entry_line",
    "is_live_inventory",
    "projects_map",
    "ProdDevPair",
    "build_prod_dev_pairs",
    "orphan_dev_databases",
    "prod_to_dev_name",
    "BackupPlanDryRun",
    "ExcludedDatabase",
    "build_backup_plan",
    "build_backup_plan_from_inventory",
    "build_demo_backup_plan",
    "build_discovered_backup_plan",
    "PolicyFinding",
    "PolicyReport",
    "validate_config_policy",
    "validate_configured_names_only",
    "SOURCE_LOCAL",
    "SOURCE_EXAMPLE",
    "SOURCE_CATALOG",
    "SOURCE_LIVE",
]
