"""Interactive Mercury menu — loop, prompts, dashboard, and action runners."""

from mercury.menu.dashboard import dashboard_rows
from mercury.menu.loop import MenuResult, handle_menu_choice, run_menu
from mercury.menu.main_display import (
    MENU_EXIT_LABEL,
    MENU_FOOTER,
    MENU_ITEM_INDENT,
    MENU_RETURN_LABEL,
    MENU_SECTIONS,
    MENU_SUBTITLE,
    MENU_TITLE,
    MenuItem,
    dashboard_rows as compact_status_rows,
    format_menu_bottom_option,
    menu_item,
    menu_items_by_key,
    readiness_summary,
    render_main_menu,
    render_main_menu_body,
    render_menu_help,
    render_option_menu,
    status_line,
    status_rows,
)
from mercury.menu.prompts import (
    CONTINUE_PROMPT,
    ask,
    ask_confirmation_phrase,
    ask_safe,
    ask_stripped,
    ask_yes_no,
    invalid_choice_message,
    is_valid_menu_choice,
    menu_action_keys,
    menu_option_prompt,
    menu_option_range_label,
    normalize_menu_choice,
    read_menu_option,
    set_continue_reader,
    set_prompt_reader,
    submenu_option_prompt,
    wait_for_continue,
)
from mercury.menu.runners import (
    MENU_ITEMS,
    render_menu_text,
    render_status_block,
    run_backup_batch_menu,
    run_discover_databases,
    run_environment_check,
    run_reports_and_history,
    run_restore_check_menu,
    run_schema_backup_plan,
    run_sync_plan,
    run_verify_plan,
)
from mercury.menu.subscreen import pause_and_redraw, read_submenu_choice, render_submenu

__all__ = [
    "CONTINUE_PROMPT",
    "MENU_EXIT_LABEL",
    "MENU_FOOTER",
    "MENU_ITEM_INDENT",
    "MENU_ITEMS",
    "MENU_RETURN_LABEL",
    "MENU_SECTIONS",
    "MENU_SUBTITLE",
    "MENU_TITLE",
    "MenuItem",
    "MenuResult",
    "ask",
    "ask_confirmation_phrase",
    "ask_safe",
    "ask_stripped",
    "ask_yes_no",
    "compact_status_rows",
    "dashboard_rows",
    "format_menu_bottom_option",
    "handle_menu_choice",
    "invalid_choice_message",
    "is_valid_menu_choice",
    "menu_action_keys",
    "menu_item",
    "menu_items_by_key",
    "menu_option_prompt",
    "menu_option_range_label",
    "normalize_menu_choice",
    "pause_and_redraw",
    "read_menu_option",
    "read_submenu_choice",
    "readiness_summary",
    "render_main_menu",
    "render_main_menu_body",
    "render_menu_help",
    "render_menu_text",
    "render_option_menu",
    "render_status_block",
    "render_submenu",
    "run_backup_batch_menu",
    "run_discover_databases",
    "run_environment_check",
    "run_menu",
    "run_reports_and_history",
    "run_restore_check_menu",
    "run_schema_backup_plan",
    "run_sync_plan",
    "run_verify_plan",
    "set_continue_reader",
    "set_prompt_reader",
    "status_line",
    "status_rows",
    "submenu_option_prompt",
    "wait_for_continue",
]
